"""
Orchestrator Module — Core Reasoners, Homeostatic Modulation, and Weight Calibration

Ties together G2 (Impulse -> Chain), G10 (Signal-to-Context Synthesizer), and G19 (Homeostatic Weight Calibration).
Implements the full-featured, comprehensive 12-Stage Pipeline Orchestrator to solve
the end-to-end task execution flow as specified in 04_ARCHITECTURE.md and 03_PIPELINE_MATH.md.
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple, Set
from enum import Enum
import random

from ..memory.core import EpisodicMemory, Episode, OperationalMemory, SemanticMemory, ProceduralMemory, ConsolidationGate
from ..mission.core import TaskDecomposer
from ..utility.control import HomeostaticRegulator
from ..models.agents import Agent
from ..models.task import Task, TaskStatus, create_task
from ..compliance.core import Action, GammaVeto, MaxCostRule
from ..delivery.core import DeliveryManager, MockDeliveryAdapter
from ..triggers.core import TriggerSystem, EventTrigger
from ..market_protocols.core import ProtocolRegistry, ProtocolOutcome
from ..client_psychometrics.core import ClientRiskProfile, risk_premium
from ..cold_start.core import ColdStartState
from ..utility import evaluate_decision_rule, compute_quality, VetoType, Decision, CapabilityVector
from ..config.loader import get_config

from .scheduler import AIOSScheduler
from .context import AIOSContextManager
from .tools import AIOSToolManager
from ..compliance.security import AIOSAccessManager
from ..verifier.core import Verifier
from ..memory.storage import AIOSStorageManager


@dataclass
class OrchestratorContext:
    """Structured context generated by the Signal-to-Context Synthesizer."""
    prompt: str
    situation: str
    recommended_tone: str
    priority_variables: List[str]
    pressures: Dict[str, float]
    relevant_history: List[str] = field(default_factory=list)


class SignalToContextSynthesizer:
    """
    Signal-to-Context Synthesizer (G10 / G2).
    
    Transforms the homeostatic pressures (signals) and memory history
    into a structured OrchestratorContext (Prompt / Task Guide) for LLM decision making.
    
    Formula:
        Chain/Context = f(Impulse, Memory, Context)
    """
    
    def __init__(self, memory: Optional[EpisodicMemory] = None):
        self.memory = memory or EpisodicMemory()
        
    def synthesize(
        self,
        metrics: Dict[str, float],
        task: Any = None,
        regulator: Optional[HomeostaticRegulator] = None,
    ) -> OrchestratorContext:
        """
        Synthesize the active homeostatic signals and long-term memory into structured guide.
        
        Args:
            metrics: Active agent metrics (balance, success_rate, stress_level, etc.)
            task: Current candidate task (optional)
            regulator: HomeostaticRegulator instance to compute pressures (optional)
            
        Returns:
            OrchestratorContext containing structured prompts and variables.
        """
        regulator = regulator or HomeostaticRegulator()
        
        # 1. Calculate homeostatic pressures
        pressures = regulator.update_all(metrics)
        
        # 2. Get urgent variables (sorted descending by pressure signal)
        sorted_pressures = sorted(pressures.items(), key=lambda x: x[1], reverse=True)
        urgent = [k for k, v in sorted_pressures if v > 0.0]
        if not urgent:
            urgent = ["optimal_equilibrium"]
            
        # 3. Retrieve relevant lessons from strategic memory matching the top pressure keyword
        memories = []
        if urgent and urgent[0] != "optimal_equilibrium":
            memories = self.memory.recall_strategies(urgent[0])
            if not memories:
                # Try fallback on general tag
                memories = self.memory.recall_strategies("default")
                
        # 4. Classify active situation profile
        mode = regulator.get_mode()
        situation = f"Mode: {mode.upper()} | Critical drives: {', '.join(urgent[:3])}"
        
        # 5. Classify tone and recommended action guidelines
        if mode == "survival":
            tone = "CONSERVATIVE / SURVIVAL ONLY"
            guidelines = "Minimize tool cost. Focus purely on task completion. Reject speculative ideas."
        elif mode == "growth":
            tone = "EXPLORATIVE / LEARNING OR REPUTATION"
            guidelines = "Invest in long-term reputation and knowledge acquisition. Budget constraints relaxed."
        else:
            tone = "BALANCED / STEADY STATE"
            guidelines = "Maintain normal operations. Calibrate costs against time and expected quality."
            
        # 6. Build the prompt
        task_title = getattr(task, "title", "None") if task else "None"
        prompt = (
            f"=== ORCHESTRATOR INSTRUCTIONS ===\n"
            f"Active Situation: {situation}\n"
            f"Recommended Tone: {tone}\n"
            f"Guidelines: {guidelines}\n"
            f"Target Task: {task_title}\n"
            f"Top Pressures: {', '.join(f'{k}={v:.2f}' for k, v in sorted_pressures[:3])}\n"
        )
        if memories:
            prompt += f"Relevant Strategic Memories:\n" + "\n".join(f"- {m}" for m in memories[:3]) + "\n"
        prompt += "================================="
        
        return OrchestratorContext(
            prompt=prompt,
            situation=situation,
            recommended_tone=tone,
            priority_variables=urgent,
            pressures=pressures,
            relevant_history=memories,
        )


class HomeostaticUtilityModulator:
    """
    Homeostatic Utility Modulator (G10 / G19).
    
    Formula:
        U_final = U_base * f(H_pressure)
        
    Yerkes-Dodson inspired modulation curve for base utility based on total stress pressure:
    - Low pressure (total_pressure < 0.5): f = 0.5 + 0.5 * total_pressure (complacency / under-utilized)
    - Optimal zone (0.5 <= total_pressure < 1.0): f = 1.0 (peak performance)
    - Stress zone (1.0 <= total_pressure < 2.0): f = 1.0 - 0.3 * (total_pressure - 1.0) (conservative)
    - Critical zone (total_pressure >= 2.0): f = 0.1 (minimal operations / safety priority only)
    """
    
    def modulate(self, base_utility: float, pressures: Dict[str, float]) -> float:
        """
        Modulate decision utility using current homeostatic pressure vectors.
        
        Args:
            base_utility: Raw utility score computed by decision equations
            pressures: Active homeostatic metric pressures
            
        Returns:
            Modulated utility score
        """
        total_pressure = sum(max(0.0, v) for v in pressures.values())
        
        # Yerkes-Dodson inspired scaling factor
        if total_pressure < 0.5:
            f = 0.5 + 1.0 * total_pressure
            f = min(1.0, f)
        elif total_pressure < 1.0:
            f = 1.0
        elif total_pressure < 2.0:
            f = 1.0 - 0.3 * (total_pressure - 1.0)
            f = max(0.2, f)
        else:
            f = 0.1
            
        return base_utility * f


class WeightCalibrator:
    """
    Weight Calibrator (G19).
    
    A cybernetic adaptive weight calibrator. Uses homeostatic pressures
    to dynamically adjust the objective weights (profit, reputation, evolution, quality)
    towards equilibrium thresholds.
    """
    
    def __init__(self, base_weights: Optional[Dict[str, float]] = None):
        self.base_weights = base_weights or {
            "profit_weight": 0.30,
            "reputation_weight": 0.25,
            "evolution_weight": 0.20,
            "quality_weight": 0.25,
        }
        
    def calibrate(self, pressures: Dict[str, float]) -> Dict[str, float]:
        """
        Dynamically adjust base utility weights according to current pressures.
        
        Args:
            pressures: Active pressure signals (e.g. balance, success_rate, stress_level, knowledge)
            
        Returns:
            Calibrated and normalized weights dictionary.
        """
        calibrated = dict(self.base_weights)
        
        # Survival adjustments
        balance_p = pressures.get("balance", 0.0)
        success_p = pressures.get("success_rate", 0.0)
        stress_p = pressures.get("stress_level", 0.0)
        
        if balance_p > 0.3:
            # High balance pressure -> boost profit weight to earn money
            calibrated["profit_weight"] += balance_p * 0.5
            calibrated["evolution_weight"] = max(0.05, calibrated["evolution_weight"] - balance_p * 0.3)
            
        if success_p > 0.3 or stress_p > 0.3:
            # High stress or failure rate -> prioritize high quality & lower risk actions
            calibrated["quality_weight"] += max(success_p, stress_p) * 0.4
            calibrated["evolution_weight"] = max(0.05, calibrated["evolution_weight"] - 0.1)
            
        # Growth adjustments
        knowledge_p = pressures.get("knowledge", 0.0)
        reputation_p = pressures.get("reputation", 0.0)
        
        if knowledge_p > 0.3:
            calibrated["evolution_weight"] += knowledge_p * 0.4
            
        if reputation_p > 0.3:
            calibrated["reputation_weight"] += reputation_p * 0.4
            
        # Ensure all adjusted weights are positive and normalize to sum to 1.0
        for k in calibrated:
            calibrated[k] = max(0.01, calibrated[k])
            
        total = sum(calibrated.values())
        if total > 0.0:
            calibrated = {k: v / total for k, v in calibrated.items()}
            
        return calibrated


# =============================================================================
# INTEGRATED LLM ROUTER & MCP TOOL CLIENT (04_ARCHITECTURE.md compliant)
# =============================================================================

@dataclass
class SimulatedResponse:
    """Simulated LLM Completion Response matching SuperRouterClient contract."""
    text: str
    model: str
    provider_name: str
    tokens_used: int
    latency_ms: float


def calculate_token_cost(model_name: str, tokens_used: int) -> float:
    """Calculate cost of tokens based on config prices or a safe fallback rate."""
    cfg = get_config()
    # Try to find model in prices
    price_info = None
    for provider_key in ["openai", "anthropic", "ollama"]:
        provider_prices = getattr(cfg.prices, provider_key, {})
        if model_name in provider_prices:
            price_info = provider_prices[model_name]
            break
            
    if price_info is not None:
        rate = getattr(price_info, "output", 0.002)
        return (tokens_used * rate) / 1000.0
        
    return (tokens_used * 0.002) / 1000.0


def parse_response_content(text: str) -> Dict[str, Any]:
    """Parse and extract structured code blocks and JSON from LLM text."""
    import re
    import json
    result = {"raw_text": text, "extracted_code": None, "extracted_json": None}
    
    # 1. Extract markdown code blocks
    code_blocks = re.findall(r"```(?:python)?\n(.*?)\n```", text, re.DOTALL)
    if code_blocks:
        result["extracted_code"] = code_blocks[0].strip()
        
    # 2. Extract JSON blocks
    json_blocks = re.findall(r"```json\n(.*?)\n```", text, re.DOTALL)
    if json_blocks:
        try:
            result["extracted_json"] = json.loads(json_blocks[0].strip())
        except Exception as e:
            import logging
            logging.getLogger(__name__).warning(f"Suppressed error: {e}")
            
    # Fallback to general JSON extraction if curly braces are present
    if not result["extracted_json"]:
        curly_blocks = re.findall(r"({.*?})", text, re.DOTALL)
        for b in curly_blocks:
            try:
                result["extracted_json"] = json.loads(b.strip())
                break
            except (json.JSONDecodeError, ValueError):
                pass
                
    return result


class CircuitBreakerOpenException(Exception):
    """Exception raised when circuit breaker is in OPEN state."""
    pass


class CircuitBreaker:
    """
    Circuit Breaker per 10_SECURITY.md §III.2.

    Extends classic API fault-tolerance with:
      - theta_fail: failure rate threshold in sliding window
      - kappa: budget overrun multiplier (C_actual > kappa * C_predicted)
      - d_max: maximum cascade depth
      - Integration with H / PlatformRiskScore for global trip
    """
    def __init__(
        self,
        failure_threshold: int = 3,
        cooldown_seconds: float = 2.0,
        theta_fail: float = 0.5,
        window_size: int = 10,
        kappa: float = 2.0,
        d_max: int = 5,
        consecutive_successes_threshold: int = 3,
    ):
        self.failure_threshold = failure_threshold
        self.cooldown_seconds = cooldown_seconds
        self.theta_fail = theta_fail          # max failure ratio in window
        self.window_size = window_size        # sliding window size
        self.kappa = kappa                    # budget overrun multiplier
        self.d_max = d_max                    # max cascade depth
        self.consecutive_successes_threshold = consecutive_successes_threshold

        self.state = "CLOSED"
        self.failure_count = 0
        self.success_count = 0

        self.last_failure_time = None
        self._failures_window = []            # timestamps
        self._budget_violations = 0
        self._cascade_depth = 0
        self._global_risk = 0.0

    def before_call(self, H=None, platform_risk=None):
        """Check state before execution. Integrates H and PlatformRiskScore for global trip."""
        # Global trip: if H is CRITICAL or platform_risk is high, force OPEN
        if H is not None and H < 0.2:
            self.state = "OPEN"
            self._global_risk = 1.0
        if platform_risk is not None and platform_risk > 0.8:
            self.state = "OPEN"
            self._global_risk = max(self._global_risk, platform_risk)

        if self.state == "OPEN":
            if self.last_failure_time and (datetime.now() - self.last_failure_time).total_seconds() > self.cooldown_seconds:
                self.state = "HALF_OPEN"
                self.consecutive_successes = 0  # Reset when entering HALF_OPEN
            else:
                raise CircuitBreakerOpenException("Circuit Breaker is OPEN. Execution blocked.")

    def record_success(self):
        """Record success. In HALF_OPEN, need consecutive successes to close."""
        self.failure_count = 0  # Reset on success
        self.success_count += 1
        self._cascade_depth = max(0, self._cascade_depth - 1)
        self._budget_violations = 0  # Also reset budget violations

        if self.state == "HALF_OPEN":
            self.consecutive_successes += 1
            if self.consecutive_successes >= self.consecutive_successes_threshold:
                self.state = "CLOSED"
                self.consecutive_successes = 0
        else:
            self.state = "CLOSED"
            self.consecutive_successes = 0

    def record_failure(self, cost_actual=None, cost_predicted=None):
        """Record failure with optional budget overrun check."""
        now = datetime.now().timestamp()
        # Trim window BEFORE adding new failure for accurate ratio calculation
        cutoff = now - 60.0  # 1-minute sliding window
        self._failures_window = [t for t in self._failures_window if t > cutoff]
        
        # Check theta_fail threshold BEFORE adding to window
        total_recent = self.success_count + len(self._failures_window)
        self._failures_window.append(now)  # Add after ratio check
        
        if total_recent > 0 and len(self._failures_window) / total_recent > self.theta_fail:
            self.state = "OPEN"

        # Check kappa budget overrun
        if cost_actual is not None and cost_predicted is not None and cost_predicted > 0:
            if cost_actual > self.kappa * cost_predicted:
                self._budget_violations += 1
                if self._budget_violations >= 2:
                    self.state = "OPEN"

        # Check cascade depth
        self._cascade_depth += 1
        if self._cascade_depth >= self.d_max:
            self.state = "OPEN"

        self.failure_count += 1
        self.last_failure_time = datetime.now()

        if self.state == "CLOSED" and self.failure_count >= self.failure_threshold:
            self.state = "OPEN"
        elif self.state == "HALF_OPEN":
            self.state = "OPEN"


def _run_async(coro, timeout: float = 10.0):
    """
    Execute an async coroutine safely.

    FIX: Убран thread-bomb (run_coroutine_threadsafe). 
    Если уже в async контексте — await напрямую через nest_asyncio.
    Если нет — asyncio.run с таймаутом.
    """
    import asyncio
    try:
        loop = asyncio.get_running_loop()
        # Already in an async context — use nest_asyncio if available
        try:
            import nest_asyncio
            nest_asyncio.apply()
            return loop.run_until_complete(asyncio.wait_for(coro, timeout=timeout))
        except ImportError:
            # Fallback: create new thread with own loop
            import concurrent.futures
            with concurrent.futures.ThreadPoolExecutor(max_workers=1) as executor:
                future = executor.submit(asyncio.run, asyncio.wait_for(coro, timeout=timeout))
                return future.result(timeout=timeout + 5)
    except RuntimeError:
        # No running loop — use asyncio.run with timeout
        return asyncio.run(asyncio.wait_for(coro, timeout=timeout))


class AISuperRouter:
    """Integrated AI Super Router supporting 20+ free AI API providers and full fallbacks."""
    
    def __init__(self):
        self.breaker = CircuitBreaker()
        self.client = None
        
        # Dynamically import SuperRouterClient from ai_super_router
        try:
            import sys
            import os
            router_dir = os.path.join(os.path.dirname(__file__), "..", "ai_super_router")
            if router_dir not in sys.path:
                sys.path.insert(0, router_dir)
                
            from main import load_providers
            from core.client import SuperRouterClient
            
            config_path = os.path.join(router_dir, "config", "providers.yaml")
            providers = load_providers(config_path)
            
            # Check if we have at least one valid key configured
            has_configured_keys = False
            for p in providers:
                if p.api_key and not p.api_key.startswith("YOUR_"):
                    has_configured_keys = True
                    break
                    
            if has_configured_keys:
                self.client = SuperRouterClient(providers)
                _run_async(self.client.start())
        except Exception as e:
            # Fallback gracefully if any import or config fails
            self.client = None

    def route_prompt_detailed(self, system_prompt: str, user_prompt: str, fail_chance: float = 0.0) -> Any:
        """Route to appropriate LLM and return full detailed response object."""
        import time
        self.breaker.before_call()
        
        # 1. Try to run real SuperRouterClient if active and initialized
        if self.client is not None:
            try:
                # Real LLM call through SuperRouter — с таймаутом 10 сек
                response = _run_async(self.client.complete(
                    prompt=user_prompt,
                    system_prompt=system_prompt,
                    max_tokens=2048,
                ), timeout=10.0)
                self.breaker.record_success()
                return response
            except (RuntimeError, ConnectionError, TimeoutError) as e:
                # Fallback to simulated block if real router fails
                self.breaker.record_failure()
                logger.warning(f"Router call failed: {e}")

        # 2. Simulated/Mock fallback with exponential retry and circuit breaker protection
        def attempt_call():
            if fail_chance > 0.0 and random.random() < fail_chance:
                raise RuntimeError("Transient LLM Provider Error / Timeout")
            # Simulate a realistic coding response with markdown code block
            return SimulatedResponse(
                text="Here is the python code:\n```python\ndef solution():\n    return 42\n```",
                model="llama-3.3-70b",
                provider_name="Groq",
                tokens_used=random.randint(100, 350),
                latency_ms=25.0
            )

        delay = 0.01
        last_exception = None
        for attempt in range(3):
            try:
                res = attempt_call()
                self.breaker.record_success()
                return res
            except Exception as e:
                last_exception = e
                time.sleep(delay)
                delay *= 2.0
                
        # Record failure on the circuit breaker if all retries failed
        self.breaker.record_failure()
        raise last_exception

    def route_prompt(self, system_prompt: str, user_prompt: str, fail_chance: float = 0.0) -> str:
        """Backward-compatible string route_prompt."""
        res = self.route_prompt_detailed(system_prompt, user_prompt, fail_chance)
        return res.text


class MCPToolClient:
    """Model Context Protocol (MCP) Client for execution."""

    def execute_tool(self, tool_name: str, params: Dict[str, Any]) -> Dict[str, Any]:
        """Call external CLI tools or sandbox environments via MCP protocol."""
        import subprocess
        import json

        cli_tools = {
            "python": ["python", "-c"],
            "bash": ["bash", "-c"],
            "python3": ["python3", "-c"],
            "sh": ["sh", "-c"],
        }

        command = params.get("command", params.get("code", params.get("input", "")))

        if tool_name in cli_tools:
            try:
                base_cmd = cli_tools[tool_name]
                result = subprocess.run(
                    base_cmd + [command],
                    capture_output=True,
                    text=True,
                    timeout=30,
                    cwd=params.get("cwd", None)
                )
                return {
                    "success": result.returncode == 0,
                    "tool": tool_name,
                    "output": result.stdout if result.returncode == 0 else result.stderr,
                    "returncode": result.returncode
                }
            except subprocess.TimeoutExpired:
                return {
                    "success": False,
                    "tool": tool_name,
                    "output": "Execution timed out after 30 seconds."
                }
            except Exception as e:
                return {
                    "success": False,
                    "tool": tool_name,
                    "output": str(e)
                }

        return {
            "success": False,
            "tool": tool_name,
            "output": f"Unknown tool '{tool_name}'. Supported: {list(cli_tools.keys())}. "
                      f"Received params: {json.dumps(params, default=str)[:200]}"
        }

# =============================================================================
# DYNAMIC TASK DECOMPOSER
# =============================================================================

class Orchestrator:
    """
    Unified 12-Stage Pipeline Orchestrator.
    Ties together all AIOS kernel managers to execute tasks end-to-end.
    """
    
    def __init__(self, core_agent: Agent, veto: Optional[GammaVeto] = None):
        self.core_agent = core_agent
        self.scheduler = AIOSScheduler()
        self.context_mgr = AIOSContextManager()
        self.storage_mgr = AIOSStorageManager(filepath="storage_memory.json")
        self.tool_mgr = AIOSToolManager()
        self.access_mgr = AIOSAccessManager(veto or GammaVeto([MaxCostRule(max_cost=100.0)]))
        self.homeo = HomeostaticRegulator()
        self.weights_calibrator = WeightCalibrator()

        self.decomposer = TaskDecomposer()
        
        # Integrations
        self.ai_super_router = AISuperRouter()
        self.mcp_client = MCPToolClient()
        self.protocol_registry = ProtocolRegistry()
        self.delivery_mgr = DeliveryManager()
        self.delivery_mgr.register(MockDeliveryAdapter())
        self.cold_start = ColdStartState()
        self.trigger_system = TriggerSystem()
        self.trigger_system.register(EventTrigger("task_completed_trigger", "task_completed", lambda e: e))
        
        # Memory Modules
        self.op_mem = OperationalMemory()
        self.strategic_mem = EpisodicMemory()
        self.meta_mem = SemanticMemory()
        self.procedural_mem = ProceduralMemory()
        self.consolidation_gate = ConsolidationGate(
            episodic_mem=self.strategic_mem,
            semantic_mem=self.meta_mem,
            procedural_mem=self.procedural_mem
        )
        
    def dispatch_full_cycle(self, mission_profile: str = "BALANCED") -> Dict[str, Any]:
        """
        Execute the complete, canonical 12-stage AIOS pipeline loop for the next scheduled task.
        """
        trace = []
        
        # =====================================================================
        # STAGE I: Reception & Prioritization
        # =====================================================================
        task = self.scheduler.pop_next_task()
        if not task:
            return {"status": "STALL", "reason": "No active tasks in scheduler queue"}
            
        trace.append("Stage I: Task pop successful. OWNER_DIRECT prioritization active.")

        # Cold-start: если агент новый -- применяем начальные значения
        if self.core_agent.capabilities.n_completed_tasks == 0:
            task.metadata["cold_start"] = self.cold_start.to_dict()
            trace.append("Stage I: Cold-start values applied (n_completed=0).")
        
        # =====================================================================
        # STAGE II: Context Building (StatusBlock)
        # =====================================================================
        metrics_dict = {
            "balance": self.core_agent.metrics.balance,
            "rating": self.core_agent.metrics.success_rate * 5.0,
            "quality": self.core_agent.capabilities.llm_quality,
            "active_tasks": self.core_agent.metrics.n_active_tasks,
        }
        H, stress = self.homeo.calculate_homeostasis(metrics_dict)
        
        # Semantic vector TF-IDF retrieval
        recalled = self.storage_mgr.retrieve_with_weighted_ranking(task.title, max_results=3)
        snippets = [f"{r['entry'].key}: value={r['entry'].value}" for r in recalled]
        
        status_block = self.context_mgr.render_status_block(
            homeostasis_h=H,
            deviations=[],
            remaining_plan=[task.title],
            memory_snippets=snippets
        )
        trace.append("Stage II: Context StatusBlock rendered via TF-IDF vector experiences.")

        # CCRS: оценка риска клиента по задаче
        client_risk = risk_premium(
            task_description=f"{task.title} {task.description}",
            category_median_hours=task.estimated_hours or 8.0
        )
        task.metadata["ccrs"] = client_risk
        trace.append(f"Stage II-CCRS: Client risk premium = {client_risk:.2f}")
        
        # =====================================================================
        # STAGE III: Complexity Classification + Estimates
        # =====================================================================
        class_res = self.context_mgr.classify(task)
        trace.append(f"Stage III: Task classified. Complexity={class_res['complexity_score']:.2f}")

        # MED-02: predict_estimates integration
        phi_hat, q_predicted_hat, psi_hat = predict_estimates(
            x=self.core_agent.capabilities.to_dict().get("capabilities", {}),
            category_probs={"default": 1.0},
            price=task.price or 0.0,
            n_completed=self.core_agent.capabilities.n_completed_tasks,
        )
        trace.append(f"Stage III: Estimates predicted (phi={phi_hat:.2f}, q={q_predicted_hat:.2f}, psi={psi_hat:.2f}).")
        
        # =====================================================================
        # STAGE IV: Compliance Veto (Gamma Gate Veto)
        # =====================================================================
        # Create a candidate Action and check compliance
        task_action = Action(name=f"task_action_{task.id}", resource_cost=20.0, params={})
        compliant = self.access_mgr.check_hard_veto(task_action)
        if not compliant:
            task.fail(reason="Failed Stage IV compliance veto")
            return {"status": "REJECTED_BY_COMPLIANCE", "task_id": task.id, "trace": trace}
            
        trace.append("Stage IV: Compliance Gamma-gate checks passed.")
        
        # =====================================================================
        # =====================================================================
        # STAGE V: Decision Rule Cascade
        # =====================================================================
        # MED-03: Use predict_estimates results (phi_hat, q_predicted_hat, psi_hat) from Stage III
        # instead of recomputing via compute_phi_risk_adjusted / compute_psi.

        # Compute gamma_soft from the veto system (was hardcoded to 0.0)
        gamma_soft_val = self.access_mgr.veto_system.gamma_soft(task_action)

        # U = phi_hat * (1 - min(1, gamma_soft)) — per 02_MATHEMATICAL_CORE.md §IV.11
        u_val = phi_hat * (1.0 - min(1.0, gamma_soft_val))

        h_tz_val = task.metadata.get("complexity_entropy", 0.5)
        # VoI uses phi_hat (predicted profit) instead of phi_adj
        voi_val = max(0.0, phi_hat * h_tz_val * 0.2)

        # Load decision parameters from YAML configuration
        cfg = get_config()
        psi_max = getattr(cfg.constants, "psi_max", 5.0)
        min_balance = getattr(cfg.rules.financial, "min_balance", 0.0)
        h_tz_max = getattr(cfg.constants, "h_tz_max", 1.0)
        h_clarify = getattr(cfg.constants, "h_clarify", 0.5)
        c_info_val = getattr(cfg.constants, "c_info_default", 100.0)

        # Compute actual gamma_hard from Stage IV compliance check
        g_hard = 0.0 if compliant else float('-inf')

        decision = evaluate_decision_rule(
            gamma_hard=g_hard,
            psi=psi_hat,                    # ← predicted risk from Stage III
            psi_max=psi_max,
            C_t=self.core_agent.metrics.balance,
            C_min=min_balance,
            H_TZ=h_tz_val,
            H_TZ_max=h_tz_max,
            VoI=voi_val,
            C_info=c_info_val,
            H_val=H,
            H_clarify=h_clarify,
            U_val=u_val,                    # ← based on phi_hat
            Q_predicted=q_predicted_hat,    # ← predicted quality from Stage III
            q_min=task.metadata.get("quality_requirement", 0.5),
            veto_type=VetoType.NONE,
            mission_profile=mission_profile
        )

        # REJECT only for hard compliance; DECLINE for risk/budget/utility failures
        if decision == "REJECT":
            task.fail(reason="Rejected by hard compliance veto")
            return {"status": "REJECTED_BY_COMPLIANCE", "task_id": task.id, "trace": trace}
        elif decision == "DECLINE":
            task.fail(reason="Declined: unfavorable risk/budget/utility")
            return {"status": "DECLINED_BY_DECISION_RULE", "task_id": task.id, "trace": trace}
        elif decision == "CLARIFY":
            return {"status": "CLARIFY_REQUIRED", "task_id": task.id, "trace": trace}

        trace.append(f"Stage V: Decision rule evaluated: {decision} (phi_hat={phi_hat:.2f}, psi_hat={psi_hat:.2f}, q_hat={q_predicted_hat:.2f})")

        # STAGE VI: Decomposition
        # =====================================================================
        # Generate strict, verified AtomicActions via Decomposer
        action_plan, _ = self.decomposer.decompose(task)
        trace.append(f"Stage VI: Task successfully decomposed into {len(action_plan)} strict verified actions.")
        
        # =====================================================================
        # STAGE VII: Specialist Routing (UCB1 MAB)
        # =====================================================================
        # Register functional specialties if not present
        from ..agents.core import ScoutSpecialist, WorkerSpecialist, FinanceSpecialist
        self.tool_mgr.register_specialist(ScoutSpecialist(self.core_agent))
        self.tool_mgr.register_specialist(WorkerSpecialist(self.core_agent))
        self.tool_mgr.register_specialist(FinanceSpecialist(self.core_agent))
        
        specialists_pool = ["Scout", "Worker", "Finance"]
        assigned_specialists = []
        for action in action_plan:
            spec_name = self.tool_mgr.select_best_specialist(specialists_pool)
            assigned_specialists.append((action, spec_name))
            
        trace.append("Stage VII: Specialists routed via multi-armed bandit UCB1 algorithm.")
        
        # =====================================================================
        # STAGE VIII: Вызов инструментов (Execution with Super Router & MCP)
        # =====================================================================
        execution_results = []
        all_responses = []
        execution_successful = True
        total_token_cost = 0.0
        
        for action, spec_name in assigned_specialists:
            # 1. LLM route prompt call with detailed output response
            response_obj = self.ai_super_router.route_prompt_detailed(
                system_prompt="Execute specialized subroutine",
                user_prompt=f"""You are {spec_name} executing Action: {action.name}

Task Context:
- Title: {task.title}
- Description: {task.description}
- Requirements: {getattr(task, 'requirements', 'N/A')}
- Priority: {task.priority.value if hasattr(task.priority, 'value') else task.priority}
- Deadline: {task.deadline}
- Estimated Hours: {task.estimated_hours}

Please provide the implementation or response for this action.
"""
            )
            
            all_responses.append(response_obj)

            # Parse output content (code and json extraction)
            parsed_content = parse_response_content(all_responses[-1].text)
            
            # Calculate real token cost (C_tokens) based on model prices in configuration
            cost_val = calculate_token_cost(response_obj.model, response_obj.tokens_used)
            total_token_cost += cost_val
            
            # 2. Model Context Protocol tool execution
            mcp_out = self.mcp_client.execute_tool(action.name, action.params)
            
            # Outcome simulation based on LLM quality (probabilistic)
            # Реальная проверка результата вместо random
            result_text = str(all_responses[-1].text) if all_responses and hasattr(all_responses[-1], "text") else ""
            success = (
                bool(result_text) and  # Не пустой
                len(result_text) > 10 and  # Минимальная длина
                not result_text.startswith("Error") and  # Не ошибка
                not result_text.startswith("Exception")  # Не исключение
            )
            self.tool_mgr.record_outcome(spec_name, success)
            
            execution_results.append({
                "action": action.name,
                "specialist": spec_name,
                "router_output": all_responses[-1].text,
                "parsed_output": parsed_content,
                "token_cost": cost_val,
                "mcp_output": mcp_out,
                "success": success
            })
            if not success:
                execution_successful = False
                
        # Subtract real token cost (C_tokens) from final profit calculations in later stages
        task.metadata["C_tokens"] = total_token_cost
        trace.append(f"Stage VIII: Tool call executions completed. Total Real Token Cost (C_tokens) = ${total_token_cost:.5f}")

        # Delivery: отправляем результаты через DeliveryManager
        if execution_successful and execution_results:
            delivery_payload = {
                "task_id": task.id,
                "title": task.title,
                "results": execution_results,
                "quality": q_value if 'q_value' in locals() else 0.0
            }
            delivery_result = self.delivery_mgr.send(
                task_id=task.id,
                result=delivery_payload,
                recipient="mock",
                adapter_name="mock"
            )
            trace.append(f"Stage VIII-Delivery: Delivered status={delivery_result.status}")
        
        # =====================================================================
        # STAGE IX: Оценка качества (Verifier Checkpoint)
        # =====================================================================
        # 3-level quality verification: completeness, accuracy, fullness
        # + Вызов Verifier с 5 критиками для реальной проверки
        try:
            verifier = Verifier()
            task_raw = f"{task.title}\n{task.description}"
            deliverable = all_responses[-1].text if all_responses else ""
            verifier_result = verifier.verify(
                deliverable=deliverable,
                task_raw=task_raw,
                context={"trace": trace, "execution_successful": execution_successful}
            )
            # Используем оценку Verifier (min_score / 10.0) если доступна
            if verifier_result and hasattr(verifier_result, 'min_score'):
                q_value = verifier_result.min_score / 10.0  # Нормализуем [0, 10] → [0, 1]
            else:
                q_value = compute_quality(
                    completeness=0.9 if execution_successful else 0.4,
                    accuracy=0.85 if execution_successful else 0.5,
                    fullness=0.9 if execution_successful else 0.3
                )
        except Exception as e:
            # Fallback если Verifier не доступен
            q_value = compute_quality(
                completeness=0.9 if execution_successful else 0.4,
                accuracy=0.85 if execution_successful else 0.5,
                fullness=0.9 if execution_successful else 0.3
            )
            trace.append(f"Stage IX: Verifier unavailable ({e}), using fallback Q = {q_value:.2f}")
        trace.append(f"Stage IX: Quality verifier completed. Calculated Q = {q_value:.2f}")
        
        # =====================================================================
        # STAGE X: Рефлексия и коррекция (RETRY Loop with substitution)
        # =====================================================================
        # If quality is below required target, we reflect, patch the plan, and RETRY!
        required_q = task.metadata.get("quality_requirement", 0.7)
        if q_value < required_q:
            trace.append("Stage X [RETRY ALERT]: Quality below requirement! Reflection triggered.")
            # Reflective hypothesis generation: replace failed action with optimized backup
            remedial_action = Action(name=f"remedial_patch_{task.id}", resource_cost=20.0, params={"backup": True})
            
            # Verify and execute backup action (remedial retry has higher chance of success)
            spec_name = self.tool_mgr.select_best_specialist(specialists_pool)
            # Реальная проверка результата вместо random
            result_text = str(all_responses[-1].text) if all_responses and hasattr(all_responses[-1], "text") else ""
            success = (
                bool(result_text) and
                len(result_text) > 10 and
                not result_text.startswith("Error") and
                not result_text.startswith("Exception")
            )
            self.tool_mgr.record_outcome(spec_name, success)
            
            # Recalculate Quality
            q_value = compute_quality(
                completeness=0.95 if success else 0.4,
                accuracy=0.90 if success else 0.5,
                fullness=0.95 if success else 0.3
            )
            trace.append(f"Stage X: Reflection execution complete. Remedial Quality Q_new = {q_value:.2f}")
            
        if q_value >= required_q:
            task.complete()
        else:
            task.fail(reason="Failed quality constraints after Stage X correction loop")
            return {"status": "FAILED_QUALITY_GOAL", "task_id": task.id, "trace": trace}
            
        # =====================================================================
        # STAGE XI: Запись в память
        # =====================================================================
        # Operational recording
        self.op_mem.set("task_id", task.id)
        self.op_mem.set("title", task.title)
        self.op_mem.update_metric("revenue", task.metadata.get("revenue") if "revenue" in task.metadata else 0.0)
        self.op_mem.update_metric("cost", 1.0 + task.metadata.get("C_tokens", 0.0))  # Base cost 1.0 + C_tokens
        self.op_mem.update_metric("risk", psi_hat)
        self.op_mem.update_metric("quality", q_value)
        
        # Market Protocols: проверяем риски платформы перед консолидацией
        from ..market_protocols.core import ProtocolState
        platform_risk = self.protocol_registry.get("payment_risk")
        if platform_risk:
            risk_state = ProtocolState()
            risk_result = platform_risk.run(risk_state, {"task_value": task.metadata.get("revenue", 0.0)})
            if risk_result.outcome == ProtocolOutcome.ESCALATE:
                trace.append(f"Stage XI-Protocol: Payment risk flagged — {risk_result.metadata.get('escalation_reason', 'unknown')}")

        # Consolidation to Strategic Memories
        exp = self.consolidation_gate.consolidate(self.op_mem)
        # Disk persistence via Storage Manager
        self.storage_mgr.persist(task.title, "Highly successful 12-stage completion.", importance=q_value)
        trace.append("Stage XI: Experiential operational trace persisted to storage file.")
        
        # =====================================================================
        # STAGE XII: Пересмотр миссий (Time/Pressure triggers)
        # =====================================================================
        # Review homeostatic signals and trigger calibration
        pressures = self.homeo.update_all(metrics_dict)
        calibrated_weights = self.weights_calibrator.calibrate(pressures)
        
        # High stress levels trigger immediate mission target edits
        mission_recalibrated = False
        if pressures.get("stress_level", 0.0) > 0.6:
            mission_recalibrated = True
            
        trace.append(f"Stage XII: Mission policy reviewed. Target Calibration trigger = {mission_recalibrated}")
        
        return {
            "status": "SUCCESS",
            "task_id": task.id,
            "decision": decision,
            "quality": q_value,
            "trace": trace,
            "execution_results": execution_results,
            "calibrated_weights": calibrated_weights,
            "consolidated_experience": exp,
            "mission_recalibrated": mission_recalibrated
        }


# =============================================================================
# APPENDIX A: PIPELINE MATHEMATICS SIGNATURE CONTRACTS (03_PIPELINE_MATH.md)
# =============================================================================

@dataclass
class Attachment:
    """Attachment primitive representation."""
    filename: str
    content_type: str = "text/plain"
    size_bytes: int = 0


@dataclass
class Deviation:
    """Deviation representing target metrics tracking offset."""
    metric: str
    value: float


@dataclass
class Trend:
    """Trend tracking indicator."""
    direction: str
    velocity: float


@dataclass
class MemorySnippet:
    """Recalled experiences snippet."""
    key: str
    value: str


@dataclass
class ExecutorProfile:
    """Specialist executor/agent profile."""
    name: str
    trust_score: float = 0.5


class ExecutorStatsRegistry:
    """Registry containing candidates metrics."""
    def __init__(self):
        self.data: Dict[str, Dict[str, Any]] = {}


class NoEligibleExecutorError(Exception):
    """Exception raised when no specialists satisfy minimum trust boundaries."""
    pass


class Attempt:
    """Atomic execution attempt trace."""
    def __init__(self, action_name: str, success: bool, error_reason: Optional[str] = None):
        self.action_name = action_name
        self.success = success
        self.error_reason = error_reason


class ReflectionAction(Enum):
    RETRY = "retry"
    ESCALATE = "escalate"
    ABANDON = "abandon"


# --- Stage 1 Contract ---
def classify_task(raw_text: str, attachments: list[Attachment]) -> tuple[CapabilityVector, dict[str, float], float]:
    """Returns capability requirement x vector, category probabilities mapping, and H_TZ uncertainty score."""
    # Simple simulated classification
    x = (0.8,) * 17
    p_categories = {"code": 0.6, "qa": 0.2, "dialog": 0.2}
    h_tz = 0.4
    return x, p_categories, h_tz


# --- Stage 2 Contract ---
def render_status_block(
    h: float,
    top_deviations: list[Deviation],
    trend: Trend,
    remaining_plan: list[Action] | None,
    memory_snippets: list[MemorySnippet],
    max_length: int
) -> str:
    """Pure formatting function — does NOT trigger external LLM requests."""
    lines = [
        f"Homeostasis H: {h:.2f}",
        f"Trend: {trend.direction} (v={trend.velocity:.2f})"
    ]
    for d in top_deviations:
        lines.append(f"Deviation: {d.metric}={d.value:.2f}")
    if remaining_plan:
        lines.append("Plan:")
        for action in remaining_plan:
            lines.append(f"  - {action.name}")
    for s in memory_snippets:
        lines.append(f"Snippet: {s.key} -> {s.value}")
        
    status = "\n".join(lines)
    return status[:max_length]


# --- Stage 3 Contract ---
def predict_estimates(
    x: CapabilityVector, 
    category_probs: dict[str, float], 
    price: float,
    n_completed: int = 0,
    agent_history: list | None = None,
) -> tuple[float, float, float]:
    """Predicts (phi_hat, q_predicted_hat, psi_hat) — 03_PIPELINE_MATH.md §III.1."""
    import math
    
    # x is dict[str, float] — extract values
    x_values = list(x.values()) if isinstance(x, dict) else x if isinstance(x, (list, tuple)) else []
    x_avg = sum(x_values) / len(x_values) if x_values else 0.5
    x_avg = max(0.0, min(1.0, x_avg))
    
    category_factor = category_probs.get("code", 0.5) * 0.8 + 0.2
    price_norm = min(price / 500.0, 1.0)
    
    v_ref_phi = 0.3 + 0.5 * x_avg + 0.2 * price_norm
    v_ref_q = 0.4 + 0.5 * x_avg
    v_ref_psi = 0.1 + 0.3 * (1.0 - x_avg) + 0.1 * (1.0 - category_factor)
    
    if agent_history and len(agent_history) > 0:
        prior_q, prior_psi = 0.5, 0.15
        n = len(agent_history)
        observed_q = sum(h.get("quality", prior_q) for h in agent_history) / n
        observed_psi = sum(h.get("risk", prior_psi) for h in agent_history) / n
        alpha = n / (n + 3)
        v_bayes_q = alpha * observed_q + (1 - alpha) * prior_q
        v_bayes_psi = alpha * observed_psi + (1 - alpha) * prior_psi
        v_bayes_phi = 0.3 + 0.4 * alpha + 0.3 * price_norm
    else:
        v_bayes_q = 0.5
        v_bayes_psi = 0.15
        v_bayes_phi = 0.3 + 0.2 * price_norm
    
    confidence = sum(1.0 for xi in x_values if xi > 0.6) / len(x_values) if x_values else 0.5
    v_llm_q = 0.5 + 0.4 * confidence
    v_llm_psi = 0.1 + 0.2 * (1.0 - confidence)
    v_llm_phi = 0.4 + 0.3 * confidence + 0.3 * price_norm
    
    # Ensemble weights by n_completed
    if n_completed < 5:
        w = [0.4, 0.2, 0.4]
    elif n_completed < 20:
        w = [0.2, 0.5, 0.3]
    else:
        w = [0.1, 0.7, 0.2]
    
    phi_hat = w[0] * v_ref_phi + w[1] * v_bayes_phi + w[2] * v_llm_phi
    q_predicted_hat = w[0] * v_ref_q + w[1] * v_bayes_q + w[2] * v_llm_q
    psi_hat = w[0] * v_ref_psi + w[1] * v_bayes_psi + w[2] * v_llm_psi
    
    phi_hat = max(0.0, min(1.0, phi_hat))
    q_predicted_hat = max(0.0, min(1.0, q_predicted_hat))
    psi_hat = max(0.0, min(1.0, psi_hat))
    
    return phi_hat, q_predicted_hat, psi_hat
def decide_with_pipeline_context(
    task: Task,
    x: CapabilityVector,
    h_tz: float,
    estimates: tuple[float, float, float],
    gamma_hard: float,
    gamma_soft: float,
    state: Any,  # AgentState or Agent core
    policy: Any  # PolicyParams or config
) -> tuple[Decision, str]:
    """
    Wrapper over evaluate_decision_rule per 02_MATHEMATICAL_CORE.md §IV.11-§IV.14.
    Returns decision and human-readable explanation.
    
    U = U_raw * (1 - min(1, Γ_soft)) — risk gate, not subtraction
    """
    phi_hat, q_hat, psi_hat = estimates
    
    # Check compliance hard/soft checks
    veto = VetoType.HARD if gamma_hard < -1e9 else VetoType.NONE
    
    # U = phi_hat * (1 - min(1, gamma_soft)) — no psi subtraction per §IV.11
    u_val = phi_hat * (1.0 - min(1.0, gamma_soft))
    
    # Read thresholds from state/policy, not literals
    cfg = get_config()
    psi_max = getattr(policy, 'psi_max', getattr(cfg.constants, 'psi_max', 5.0))
    c_t = getattr(state, 'balance', getattr(cfg.rules.financial, 'min_balance', 10.0))
    c_min = getattr(policy, 'c_min', 1.0)
    h_tz_max = getattr(cfg.constants, 'h_tz_max', 1.0)
    voi = getattr(policy, 'voi', 0.5)
    c_info = getattr(cfg.constants, 'c_info_default', 2.0)
    h_val = getattr(state, 'H', 0.8)
    h_clarify = getattr(cfg.constants, 'h_clarify', 0.5)
    q_min = getattr(policy, 'q_min', 0.5)
    
    dec_str = evaluate_decision_rule(
        gamma_hard=gamma_hard,
        psi=psi_hat,
        psi_max=psi_max,
        C_t=c_t,
        C_min=c_min,
        H_TZ=h_tz,
        H_TZ_max=h_tz_max,
        VoI=voi,
        C_info=c_info,
        H_val=h_val,
        H_clarify=h_clarify,
        U_val=u_val,
        Q_predicted=q_hat,
        q_min=q_min,
        veto_type=veto
    )
    
    dec = Decision(dec_str.lower())
    reason = "Passed compliance, risk, and utility bounds." if dec == Decision.EXECUTE else "Failed requirements."
    return dec, reason


# --- Stage 7 Contract ---
def select_executor(
    action: Action, 
    candidates: list[ExecutorProfile], 
    history: ExecutorStatsRegistry,
    tool_manager: AIOSToolManager | None = None
) -> ExecutorProfile:
    """
    Select appropriate specialist executor using UCB1 per 03_PIPELINE_MATH.md §VII.1.
    Raises NoEligibleExecutorError if trust limits are violated.
    """
    import math
    
    trust_min = 0.3
    eligible = [c for c in candidates if c.trust_score >= trust_min]
    if not eligible:
        raise NoEligibleExecutorError("No executor satisfies minimum trust requirements.")
    
    # If tool_manager is provided, use its UCB1 implementation
    if tool_manager is not None:
        candidate_names = [c.name for c in eligible]
        selected_name = tool_manager.select_best_specialist(candidate_names)
        # Find the corresponding ExecutorProfile
        for c in eligible:
            if c.name == selected_name:
                return c
    
    # Fallback: UCB1 implementation for cold-start
    # UCB1 = mean_reward + c * sqrt(ln(N) / n_i)
    # For cold start (n_i = 0), guarantee first selection
    c_exploration = 1.414  # sqrt(2)
    
    # Get UCB1 stats from history or use trust_score as prior reward
    best_score = -float('inf')
    best_candidate = eligible[0]
    
    for c in eligible:
        # Get historical stats
        stats = history.data.get(c.name, {"selections": 0, "rewards_sum": 0.0})
        n_i = stats.get("selections", 0)
        
        # Cold start: unselected specialist gets immediate selection
        if n_i == 0:
            return c
        
        # UCB1 formula
        mean_reward = stats.get("rewards_sum", 0.0) / n_i
        total_selections = sum(history.data.get(other.name, {"selections": 0}).get("selections", 0) for other in eligible)
        ucb_score = mean_reward + c_exploration * math.sqrt(math.log(max(1, total_selections)) / n_i)
        
        if ucb_score > best_score:
            best_score = ucb_score
            best_candidate = c
    
    return best_candidate


# --- Stage 10 Contract ---
def reflect(
    failed_action: Action,
    attempt_history: list[Attempt],
    current_psi: float,
    policy: Any
) -> tuple[ReflectionAction, str | None]:
    """Reflect on failed steps, and determine RETRY, ESCALATE, or ABANDON actions."""
    if len(attempt_history) >= 3:
        return ReflectionAction.ESCALATE, None
    if current_psi > 0.8:
        return ReflectionAction.ABANDON, None
        
    # Return alternative action name for retry
    return ReflectionAction.RETRY, f"backup_remedial_{failed_action.name}"
