"""
Parameter Calibration Module (G17)

Provides:
- ParameterCalibrator: Analyzes completed strategic experiences to recommend coefficient tuning and weight adjustments.
"""

from typing import Any, Dict, List, Optional
from pathlib import Path
import os

from ..memory.core import EpisodicMemory, Episode


class ParameterCalibrator:
    """
    ParameterCalibrator (G17).
    
    Acts as the offline Bayesian suggested feedback, inspecting consolidated
    Strategic Experiences over time to optimize risk tolerance, profit margins, and coefficients.
    """
    
    def __init__(self, memory: EpisodicMemory):
        self.memory = memory
        
    def calibrate_constants(self) -> Dict[str, Any]:
        """
        Analyze accumulated experiences to calibrate agent coefficients and thresholds.
        
        Returns:
            Dict containing recommended adjustments.
        """
        experiences = self.memory.get_experiences()
        if not experiences:
            return {"status": "No data available", "recommendations": {}}
            
        completed = [e for e in experiences if e.status == "completed"]
        failed = [e for e in experiences if e.status == "failed"]
        
        recs = {}
        
        # 1. Calibrate risk tolerance (psi_max)
        # If we failed multiple high risk tasks, suggest reducing acceptable risk tolerance
        high_risk_failures = [e for e in failed if e.risk > 0.5]
        if len(high_risk_failures) > 1:
            recs["psi_max"] = {
                "current": 1.0,
                "recommended": 0.75,
                "reason": "Multiple failures on tasks with risk > 0.5. Reduce risk tolerance threshold."
            }
            
        # 2. Calibrate alpha_rep (reputation multiplier in Phi_R consistency)
        # If reputation completes are yielding very high quality, we can amplify reputation bonus
        high_quality_completes = [e for e in completed if e.quality > 0.8]
        if len(high_quality_completes) > 2:
            recs["phi_r_alpha_rep"] = {
                "current": 0.3,
                "recommended": 0.45,
                "reason": "Consistently high completed quality. Increase reputation amplification boost."
            }
            
        # 3. Calibrate margins (optimal profit rate base)
        # Calculate the average profit margin rate for completed tasks to adjust minimum required bidding rate
        if completed:
            avg_phi = sum(e.revenue - e.cost for e in completed) / sum(e.time_spent for e in completed)
            recs["min_profit_rate"] = {
                "current": 5.0,
                "recommended": round(max(2.0, avg_phi * 0.8), 2),
                "reason": f"Average achieved profit rate is {avg_phi:.2f}. Align minimum bid requirement."
            }
            
        return {
            "status": "Success",
            "analyzed_count": len(experiences),
            "recommendations": recs
        }
        
    def save_calibrated_weights(self, recommendations: Dict[str, Any], config_path: Optional[str] = None) -> bool:
        """
        Save the calibrated parameter recommendation weights back into the config weights file.
        
        Args:
            recommendations: Suggestions generated by `calibrate_constants`
            config_path: Path to weights.yaml (optional)
            
        Returns:
            True if successfully saved, False otherwise.
        """
        if not recommendations or "recommendations" not in recommendations:
            return False
            
        recs = recommendations["recommendations"]
        if not recs:
            return False
            
        # Setup config directory
        if config_path is None:
            base_dir = Path(__file__).parent.parent.parent.parent / "config"
            config_path = str(base_dir / "weights.yaml")
            
        if not os.path.exists(config_path):
            return False
            
        try:
            with open(config_path, 'r') as f:
                content = f.read()
                
            # Perform simple, robust line replacements to preserve comments and layout
            lines = content.splitlines()
            modified = False
            
            for key, item in recs.items():
                rec_val = item["recommended"]
                # Look for matching yaml property
                for i, line in enumerate(lines):
                    stripped = line.strip()
                    if stripped.startswith(f"{key}:") or stripped.startswith(f"  {key}:") or stripped.startswith(f"    {key}:"):
                        parts = line.split(":", 1)
                        indent = len(line) - len(line.lstrip())
                        # Reconstruct line with recommended calibrated value
                        lines[i] = f"{' ' * indent}{key}: {rec_val}"
                        modified = True
                        break
                        
            if modified:

                with open(config_path, 'w') as f:
                    f.write("\n".join(lines) + "\n")
                return True
                
        except Exception:
            return False
            
        return False
