"""Event IDs and default amplitude table."""
from __future__ import annotations
from enum import Enum
from typing import Dict, Tuple

class EventID(str, Enum):
    RES_TOKENS_EXHAUSTED = "RES.TOKENS_EXHAUSTED"
    RES_TOKENS_LOW = "RES.TOKENS_LOW"
    RES_BUDGET_BLOCK = "RES.BUDGET_BLOCK"
    RES_RATE_LIMIT = "RES.RATE_LIMIT"
    EXT_ORDER_REJECTED = "EXT.ORDER_REJECTED"
    EXT_PROPOSAL_REJECTED = "EXT.PROPOSAL_REJECTED"
    EXT_COMPLIANCE_HIT = "EXT.COMPLIANCE_HIT"
    EXT_PLATFORM_WARNING = "EXT.PLATFORM_WARNING"
    EXT_PROVIDER_WARNING = "EXT.PROVIDER_WARNING"
    EXT_SECURITY_WARNING = "EXT.SECURITY_WARNING"
    EXT_PAYMENT_OVERDUE = "EXT.PAYMENT_OVERDUE"
    EXT_DISPUTE_OPENED = "EXT.DISPUTE_OPENED"
    EXT_REPUTATION_HIT = "EXT.REPUTATION_HIT"
    EXEC_NO_PROGRESS = "EXEC.NO_PROGRESS"
    EXEC_VERIFIER_FAIL = "EXEC.VERIFIER_FAIL"
    EXEC_LOOP_DETECTED = "EXEC.LOOP_DETECTED"
    EXEC_DEAD_END = "EXEC.DEAD_END"
    EXEC_STEP_OK = "EXEC.STEP_OK"
    EXEC_TASK_DONE = "EXEC.TASK_DONE"
    EXEC_TASK_FAILED = "EXEC.TASK_FAILED"
    IDLE_HEARTBEAT = "IDLE.HEARTBEAT"
    IDLE_QUEUE_EMPTY = "IDLE.QUEUE_EMPTY"
    IDLE_NO_SIGNIFICANT_WORK = "IDLE.NO_SIGNIFICANT_WORK"
    OUT_BETTER_THAN_EXPECTED = "OUT.BETTER_THAN_EXPECTED"
    OUT_WORSE_THAN_EXPECTED = "OUT.WORSE_THAN_EXPECTED"
    OUT_BLOCK_CLEARED = "OUT.BLOCK_CLEARED"
    OWNER_TASK_RECEIVED = "OWNER.TASK_RECEIVED"
    OWNER_EMERGENCY = "OWNER.EMERGENCY"
    TOOL_FAIL = "TOOL.FAIL"
    MEMORY_GAP = "MEMORY.GAP"
    DEF_ITEM_ADDED = "DEF.ITEM_ADDED"
    DEF_ITEM_DONE = "DEF.ITEM_DONE"
    DEF_ITEM_OVERDUE = "DEF.ITEM_OVERDUE"
    SYS_CB_OPEN = "SYS.CB_OPEN"
    SYS_CB_GLOBAL_TRIP = "SYS.CB_GLOBAL_TRIP"
    SYS_HITL_TIMEOUT = "SYS.HITL_TIMEOUT"

DEFAULT_AMPLITUDES: Dict[str, Tuple[float, float]] = {
    "RES.TOKENS_EXHAUSTED": (0.55, 0.0),
    "RES.TOKENS_LOW": (0.22, 0.0),
    "RES.BUDGET_BLOCK": (0.50, 0.0),
    "RES.RATE_LIMIT": (0.20, 0.0),
    "EXT.ORDER_REJECTED": (0.25, 0.0),
    "EXT.PROPOSAL_REJECTED": (0.22, 0.0),
    "EXT.COMPLIANCE_HIT": (0.55, 0.0),
    "EXT.PLATFORM_WARNING": (0.40, 0.0),
    "EXT.PROVIDER_WARNING": (0.35, 0.0),
    "EXT.SECURITY_WARNING": (0.60, 0.0),
    "EXT.PAYMENT_OVERDUE": (0.35, 0.0),
    "EXT.DISPUTE_OPENED": (0.40, 0.0),
    "EXT.REPUTATION_HIT": (0.35, 0.0),
    "EXEC.NO_PROGRESS": (0.22, 0.0),
    "EXEC.VERIFIER_FAIL": (0.28, 0.0),
    "EXEC.LOOP_DETECTED": (0.65, 0.0),
    "EXEC.DEAD_END": (0.60, 0.0),
    "EXEC.STEP_OK": (-0.04, 0.16),
    "EXEC.TASK_DONE": (-0.20, 0.38),
    "EXEC.TASK_FAILED": (0.40, 0.0),
    "OUT.BETTER_THAN_EXPECTED": (-0.05, 0.30),
    "OUT.WORSE_THAN_EXPECTED": (0.28, 0.0),
    "OUT.BLOCK_CLEARED": (-0.18, 0.28),
    "OWNER.TASK_RECEIVED": (0.05, 0.08),
    "OWNER.EMERGENCY": (0.70, 0.0),
    "TOOL.FAIL": (0.30, 0.0),
    "MEMORY.GAP": (0.18, 0.0),
    "DEF.ITEM_DONE": (-0.08, 0.15),
    "DEF.ITEM_OVERDUE": (0.12, 0.0),
    "DEF.ITEM_ADDED": (0.02, 0.0),
    "IDLE.HEARTBEAT": (0.0, 0.0),
    "IDLE.QUEUE_EMPTY": (0.0, 0.0),
    "IDLE.NO_SIGNIFICANT_WORK": (0.0, 0.0),
    "SYS.CB_OPEN": (0.45, 0.0),
    "SYS.CB_GLOBAL_TRIP": (0.70, 0.0),
    "SYS.HITL_TIMEOUT": (0.30, 0.0),
}

MAJOR_SLOW_EVENTS = frozenset({
    "EXEC.LOOP_DETECTED", "EXEC.DEAD_END", "EXEC.TASK_FAILED",
    "EXT.COMPLIANCE_HIT", "EXT.SECURITY_WARNING",
    "RES.TOKENS_EXHAUSTED", "RES.BUDGET_BLOCK", "OWNER.EMERGENCY",
    "SYS.CB_GLOBAL_TRIP",
})

SIGNIFICANT_WORK_EVENTS = frozenset({
    "EXEC.STEP_OK", "EXEC.TASK_DONE", "OUT.BLOCK_CLEARED", "DEF.ITEM_DONE",
})
